CorinneBundle\Entity\Categorie:
    type: entity
    table: null
    repositoryClass: CorinneBundle\Repository\CategorieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomcat:
            type: string
            length: 255
        source:
            type: string
            length: 255
        alt:
            type: string
            length: 255
    oneToMany:
        souscategorie:
            targetEntity: CorinneBundle\Entity\SousCategorie
            mappedBy: categorie
            nullable: false
        objet:
            targetEntity: CorinneBundle\Entity\Objet
            mappedBy: categ
            nullable: false

    lifecycleCallbacks: {  }
