event_index:
    path:     /
    defaults: { _controller: "CorinneBundle:Event:index" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "CorinneBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "CorinneBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "CorinneBundle:Event:delete" }
    methods:  [GET, POST]
